import { Product, Testimonial } from "./types";

export const products: Product[] = [
  {
    id: "choc-chip-classic",
    name: "Classic Chocolate Chip",
    description: "Our signature cookie loaded with premium chocolate chips.",
    longDescription:
      "Baked fresh every morning, our Classic Chocolate Chip cookie is the one that started it all. We use only the finest Belgian chocolate chips folded into a buttery, brown-sugar dough that bakes up perfectly crispy on the edges and irresistibly gooey in the center. Every bite is pure nostalgia.",
    price: 3.5,
    category: "cookies",
    image: "https://freshaprilflours.com/wp-content/uploads/2020/12/classic-ccc-RECIPE-CARD.jpg",
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 312,
    ingredients: ["Butter", "Brown Sugar", "Belgian Chocolate Chips", "Flour", "Eggs", "Vanilla"],
    isBestseller: true,
    isFeatured: true,
    calories: 280,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
  {
    id: "double-fudge-brownie",
    name: "Double Fudge Brownie Cookie",
    description: "Rich, fudgy brownie meets chewy cookie in one decadent bite.",
    longDescription:
      "Can't decide between a brownie and a cookie? You don't have to. Our Double Fudge Brownie Cookie combines the dense, chocolatey richness of a brownie with the satisfying chew of a cookie. Loaded with dark chocolate chunks and a dusting of cocoa powder, this one is for the true chocoholics.",
    price: 4.0,
    category: "cookies",
    image: "https://yogaofcooking.co/wp-content/uploads/2020/06/double-chocolate-brownie-cookies-1.jpg",
    badge: "Fan Favorite",
    rating: 4.8,
    reviewCount: 198,
    ingredients: ["Dark Chocolate", "Cocoa Powder", "Butter", "Sugar", "Eggs", "Flour"],
    isBestseller: true,
    isFeatured: true,
    calories: 320,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
  {
    id: "strawberry-cheesecake-cookie",
    name: "Strawberry Cheesecake Cookie",
    description: "Cream cheese dough swirled with fresh strawberry jam.",
    longDescription:
      "A dreamy mashup of your favorite desserts. Our Strawberry Cheesecake Cookie features a tangy cream cheese dough studded with white chocolate chips and swirled with house-made strawberry jam. It's soft, pillowy, and absolutely irresistible — like cheesecake you can hold in your hand.",
    price: 4.25,
    category: "cookies",
    image: "https://inbloombakery.com/wp-content/uploads/2025/02/Strawberry-Cheesecake-Cookies-18.jpg",
    badge: "New",
    rating: 4.7,
    reviewCount: 87,
    ingredients: ["Cream Cheese", "Strawberry Jam", "White Chocolate", "Butter", "Flour"],
    isFeatured: true,
    calories: 295,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
  {
    id: "peanut-butter-oat",
    name: "Peanut Butter Oat Cookie",
    description: "Hearty oats and creamy peanut butter in every chewy bite.",
    longDescription:
      "For those who like a little substance with their sweetness. Our Peanut Butter Oat Cookie is packed with rolled oats, natural peanut butter, and a drizzle of honey. It's chewy, nutty, and just sweet enough — the perfect afternoon pick-me-up with a glass of cold milk.",
    price: 3.75,
    category: "cookies",
    image: "https://wildwildwhisk.com/wp-content/uploads/2018/05/Snickerdoodle-Cookies-2.jpg",
    rating: 4.6,
    reviewCount: 143,
    ingredients: ["Peanut Butter", "Rolled Oats", "Honey", "Butter", "Brown Sugar"],
    calories: 310,
    allergens: ["Gluten", "Peanuts", "Dairy"],
  },
  {
    id: "snickerdoodle",
    name: "Snickerdoodle",
    description: "Soft, pillowy cinnamon-sugar perfection.",
    longDescription:
      "A timeless classic done right. Our Snickerdoodle is rolled generously in cinnamon sugar before baking, creating a crackly, sparkly exterior that gives way to a soft, pillowy center. The cream of tartar gives it that signature tangy bite that keeps you coming back for more.",
    price: 3.25,
    category: "cookies",
    image: "https://www.cookingclassy.com/wp-content/uploads/2017/06/snickerdoodles-40.jpg",
    rating: 4.7,
    reviewCount: 221,
    ingredients: ["Cinnamon", "Sugar", "Cream of Tartar", "Butter", "Flour", "Eggs"],
    calories: 260,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
  {
    id: "lemon-lavender",
    name: "Lemon Lavender Cookie",
    description: "Bright citrus and floral lavender in a delicate shortbread.",
    longDescription:
      "Light, elegant, and utterly refreshing. Our Lemon Lavender Cookie is a buttery shortbread infused with fresh lemon zest and culinary lavender, finished with a lemon glaze that crackles as you bite in. It's the cookie equivalent of a sunny afternoon.",
    price: 4.0,
    category: "cookies",
    image: "https://thebeachhousekitchen.com/wp-content/uploads/2017/03/Lemon-Lavender-Shortbread-Cookies-1-of-1-6.jpg",
    badge: "Seasonal",
    rating: 4.5,
    reviewCount: 64,
    ingredients: ["Lemon Zest", "Lavender", "Butter", "Powdered Sugar", "Flour"],
    calories: 240,
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "classic-vanilla-shake",
    name: "Classic Vanilla Bean Shake",
    description: "Velvety smooth shake made with real Madagascar vanilla beans.",
    longDescription:
      "Sometimes simple is best. Our Classic Vanilla Bean Shake is made with premium vanilla ice cream, whole milk, and real Madagascar vanilla bean paste. Thick, creamy, and perfectly sweet — it's the shake that pairs with everything on our menu.",
    price: 6.5,
    category: "shakes",
    image: "https://www.foodandwine.com/thmb/aYv9IwIyM4EKLL0o7W1CUSfjXzU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Vanilla-Milkshake-FT-MAG-RECIPE-0325-4ad53abc27a74f7687e510cc17d28d1d.jpg",
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 276,
    ingredients: ["Vanilla Ice Cream", "Whole Milk", "Madagascar Vanilla Bean", "Whipped Cream"],
    isBestseller: true,
    isFeatured: true,
    calories: 480,
    allergens: ["Dairy"],
  },
  {
    id: "triple-choc-shake",
    name: "Triple Chocolate Shake",
    description: "Chocolate ice cream, chocolate syrup, and chocolate chips blended together.",
    longDescription:
      "For the chocolate lover who refuses to compromise. Our Triple Chocolate Shake layers chocolate ice cream, house-made chocolate fudge syrup, and a handful of mini chocolate chips into one gloriously indulgent drink. Topped with whipped cream and a chocolate drizzle, it's a dessert in a cup.",
    price: 7.0,
    category: "shakes",
    image: "https://pintsizedbaker.com/wp-content/uploads/2013/08/Triple-Chocolate-Milkshakes-30.jpg",
    badge: "Fan Favorite",
    rating: 4.8,
    reviewCount: 189,
    ingredients: ["Chocolate Ice Cream", "Chocolate Fudge Syrup", "Chocolate Chips", "Whole Milk"],
    isBestseller: true,
    isFeatured: true,
    calories: 620,
    allergens: ["Dairy"],
  },
  {
    id: "strawberry-dream-shake",
    name: "Strawberry Dream Shake",
    description: "Fresh strawberries blended with creamy vanilla ice cream.",
    longDescription:
      "Made with real, fresh strawberries — never artificial flavoring. Our Strawberry Dream Shake blends ripe strawberries with creamy vanilla ice cream and a splash of strawberry puree for a vibrant, fruity shake that tastes like summer in every sip. Topped with a fresh strawberry and whipped cream.",
    price: 6.75,
    category: "shakes",
    image: "https://www.thehungrybites.com/wp-content/uploads/2023/06/Strawberry-milkshake-frappuccino-featured.jpg",
    badge: "New",
    rating: 4.7,
    reviewCount: 112,
    ingredients: ["Fresh Strawberries", "Vanilla Ice Cream", "Strawberry Puree", "Whole Milk"],
    isFeatured: true,
    calories: 510,
    allergens: ["Dairy"],
  },
  {
    id: "salted-caramel-shake",
    name: "Salted Caramel Shake",
    description: "House-made caramel sauce with a pinch of sea salt.",
    longDescription:
      "The perfect balance of sweet and salty. Our Salted Caramel Shake is built on a base of caramel ice cream, swirled with house-made caramel sauce, and finished with a generous pinch of flaky sea salt. It's sophisticated, indulgent, and completely addictive.",
    price: 7.25,
    category: "shakes",
    image: "https://www.prairiefarms.com/wp-content/uploads/files/2023/beverage-CookiesNCreamMilkShake.jpg",
    rating: 4.8,
    reviewCount: 154,
    ingredients: ["Caramel Ice Cream", "House Caramel Sauce", "Sea Salt", "Whole Milk"],
    calories: 560,
    allergens: ["Dairy"],
  },
  {
    id: "cookies-cream-shake",
    name: "Cookies & Cream Shake",
    description: "Crushed Oreos blended into a thick, creamy vanilla base.",
    longDescription:
      "Our signature shake — and for good reason. The Cookies & Cream Shake blends crushed chocolate sandwich cookies into a thick vanilla ice cream base, creating a perfectly speckled, impossibly creamy shake. It's the ultimate cookies-and-shakes experience in one glass.",
    price: 7.0,
    category: "shakes",
    image: "https://www.unicornsinthekitchen.com/wp-content/uploads/2019/01/Cookies-and-cream-milkshake.jpg",
    badge: "Signature",
    rating: 4.9,
    reviewCount: 298,
    isBestseller: true,
    calories: 590,
    allergens: ["Gluten", "Dairy"],
    ingredients: ["Vanilla Ice Cream", "Chocolate Sandwich Cookies", "Whole Milk", "Whipped Cream"],
  },
  {
    id: "matcha-shake",
    name: "Matcha Green Tea Shake",
    description: "Ceremonial grade matcha blended with sweet cream ice cream.",
    longDescription:
      "For the adventurous palate. Our Matcha Green Tea Shake uses ceremonial-grade Japanese matcha whisked into a sweet cream ice cream base. It's earthy, slightly bitter, and beautifully balanced with a touch of honey. A sophisticated shake that's as beautiful as it is delicious.",
    price: 7.5,
    category: "shakes",
    image: "https://cdn.shopify.com/s/files/1/0659/8043/2572/files/20241105221631-matcha-milkshake_001.jpg?v=1730844993&width=1000&height=1000",
    badge: "Seasonal",
    rating: 4.6,
    reviewCount: 78,
    calories: 440,
    allergens: ["Dairy"],
    ingredients: ["Ceremonial Matcha", "Sweet Cream Ice Cream", "Honey", "Whole Milk"],
  },
  {
    id: "cookie-shake-bundle",
    name: "Cookie & Shake Bundle",
    description: "Any 2 cookies + any shake — the perfect combo deal.",
    longDescription:
      "Why choose when you can have both? Our Cookie & Shake Bundle lets you pick any two cookies from our menu paired with any shake of your choice. It's the ultimate Cookies & Shakes Co. experience and our most popular order. Perfect for a solo treat or sharing with someone special.",
    price: 12.99,
    category: "bundles",
    image: "https://pprotein.imgix.net/production/a/product/PDPCarousel_2_CookiesCream_Combo_2025-09-05-194558_dkev.jpg?ar=899%3A899&auto=format%2Ccompress&fit=crop&ixlib=php-3.1.0&s=c6ed9f0de55379a71b0113e2b282919c",
    badge: "Best Value",
    rating: 5.0,
    reviewCount: 203,
    isFeatured: true,
    isBestseller: true,
    calories: 0,
    allergens: ["Varies"],
    ingredients: ["Your choice of 2 cookies", "Your choice of 1 shake"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah M.",
    avatar: "https://i.guim.co.uk/img/media/07501c52d82cda65e32e9d77f11027cedd17da6d/0_277_978_587/master/978.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=4b8e54d2af1d988b26b2d1c1ac89f97d",
    rating: 5,
    text: "The Classic Chocolate Chip cookie is hands down the best I've ever had. It arrived warm and gooey — I literally couldn't wait to eat it. My whole family is obsessed!",
    product: "Classic Chocolate Chip",
  },
  {
    id: "t2",
    name: "James T.",
    avatar: "https://s3.amazonaws.com/arc-authors/cmg/8adde958-cd42-477c-9467-0ee150778a71.png",
    rating: 5,
    text: "I ordered the Triple Chocolate Shake and the Double Fudge Brownie Cookie together and it was a religious experience. The shake was so thick I could barely use the straw — perfect.",
    product: "Triple Chocolate Shake",
  },
  {
    id: "t3",
    name: "Priya K.",
    avatar: "https://media.licdn.com/dms/image/v2/D4D03AQFjb0oGgSOYPA/profile-displayphoto-shrink_200_200/B4DZZCoiL8G8AY-/0/1744874647031?e=2147483647&v=beta&t=iz-x6HzQIMtn31vtR_7FQLb0f3k09LJMyTJzm42hHDI",
    rating: 5,
    text: "The Strawberry Cheesecake Cookie is unlike anything I've tasted before. You can tell they use real ingredients — the strawberry jam is incredible. Will be ordering weekly!",
    product: "Strawberry Cheesecake Cookie",
  },
  {
    id: "t4",
    name: "Marcus L.",
    avatar: "https://i.scdn.co/image/ab6761610000e5ebde96c6aea2eec323014eb1a3",
    rating: 5,
    text: "Got the Cookie & Shake Bundle for my daughter's birthday and she was over the moon. Fast delivery, beautiful packaging, and the cookies were still soft. 10/10 would recommend.",
    product: "Cookie & Shake Bundle",
  },
  {
    id: "t5",
    name: "Emily R.",
    avatar: "https://m.media-amazon.com/images/M/MV5BZjliYzIwNzgtYTM3OS00YjBkLTgzYzYtZTA2MTdkNGMwNTdlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rating: 5,
    text: "The Salted Caramel Shake is my new obsession. That balance of sweet and salty is just perfect. I've already ordered it three times this month and I have zero regrets.",
    product: "Salted Caramel Shake",
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/menu", label: "Menu" },
  { href: "/about", label: "About Us" },
  { href: "/contact", label: "Contact" },
];

export const getFeaturedProducts = () => products.filter((p) => p.isFeatured);
export const getBestsellers = () => products.filter((p) => p.isBestseller);
export const getProductById = (id: string) => products.find((p) => p.id === id);
export const getProductsByCategory = (category: string) =>
  category === "all" ? products : products.filter((p) => p.category === category);
